# Generated by Django 2.2.13 on 2020-06-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
