# Generated by Django 2.2.13 on 2020-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200621_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='id',
            field=models.AutoField(auto_created=True, default=9, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
