# Generated by Django 2.2.13 on 2020-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_cv_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='award',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='community_services',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='contact_details',
            field=models.TextField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='educational_background',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='research_experience',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
